### ISSUE TITLE
Not working (latest beta-release)

### ISSUE THREAD

**Issue by ImInTheICU** [GarryyBD/versatools#23]
When running src/main.py it just closes with no error.

When running EXE verison...
![image](https://github.com/GarryyBD/versatools/assets/111275373/c9ea23e5-5881-41e0-bc52-10c5d34d7f74)

Also the follow bot is still bugging, this is seeming like a program problem and not a capsolver problem
```
Failed: {"errors":[{"code":0,"message":"Challenge failed to authorize request"}]}
Failed: {"code":0,"message":"Token Validation Failed"}
Failed: Expecting value: line 1 column 1 (char 0)
```

**Comment by GarryyBD** [comment]
First error is explicit. You need to install Google Chrome since Versatools uses it to display its GUI.

`Failed: {"errors":[{"code":0,"message":"Challenge failed to authorize request"}]}` means captcha failed

`Failed: {"code":0,"message":"Token Validation Failed"}` means csrf token failed, does this error happen often?

`Failed: Expecting value: line 1 column 1 (char 0)` means Roblox returned an HTML document. Probably meaning that cookie is invalid
